INSERT INTO languages (language_name, language_mark) VALUES('English', 'en');
INSERT INTO languages (language_name, language_mark) VALUES('Afar', 'aa');
INSERT INTO languages (language_name, language_mark) VALUES('Abkhazian', 'ab');
INSERT INTO languages (language_name, language_mark) VALUES('Afrikaans', 'af');
INSERT INTO languages (language_name, language_mark) VALUES('Amharic', 'am');
INSERT INTO languages (language_name, language_mark) VALUES('Arabic', 'ar');
INSERT INTO languages (language_name, language_mark) VALUES('Assamese', 'as');
INSERT INTO languages (language_name, language_mark) VALUES('Aymara', 'ay');
INSERT INTO languages (language_name, language_mark) VALUES('Azerbaijani', 'az');
INSERT INTO languages (language_name, language_mark) VALUES('Bashkir', 'ba');
INSERT INTO languages (language_name, language_mark) VALUES('Belarusian', 'be');
INSERT INTO languages (language_name, language_mark) VALUES('Bulgarian', 'bg');
INSERT INTO languages (language_name, language_mark) VALUES('Bihari', 'bh');
INSERT INTO languages (language_name, language_mark) VALUES('Bislama', 'bi');
INSERT INTO languages (language_name, language_mark) VALUES('Bengali/Bangla', 'bn');
INSERT INTO languages (language_name, language_mark) VALUES('Tibetan', 'bo');
INSERT INTO languages (language_name, language_mark) VALUES('Breton', 'br');
INSERT INTO languages (language_name, language_mark) VALUES('Catalan', 'ca');
INSERT INTO languages (language_name, language_mark) VALUES('Corsican', 'co');
INSERT INTO languages (language_name, language_mark) VALUES('Czech', 'cs');
INSERT INTO languages (language_name, language_mark) VALUES('Welsh', 'cy');
INSERT INTO languages (language_name, language_mark) VALUES('Danish', 'da');
INSERT INTO languages (language_name, language_mark) VALUES('German', 'de');
INSERT INTO languages (language_name, language_mark) VALUES('Bhutani', 'dz');
INSERT INTO languages (language_name, language_mark) VALUES('Greek', 'el');
INSERT INTO languages (language_name, language_mark) VALUES('Esperanto', 'eo');
INSERT INTO languages (language_name, language_mark) VALUES('Spanish', 'es');
INSERT INTO languages (language_name, language_mark) VALUES('Estonian', 'et');
INSERT INTO languages (language_name, language_mark) VALUES('Basque', 'eu');
INSERT INTO languages (language_name, language_mark) VALUES('Persian', 'fa');
INSERT INTO languages (language_name, language_mark) VALUES('Finnish', 'fi');
INSERT INTO languages (language_name, language_mark) VALUES('Fiji', 'fj');
INSERT INTO languages (language_name, language_mark) VALUES('Faeroese', 'fo');
INSERT INTO languages (language_name, language_mark) VALUES('French', 'fr');
INSERT INTO languages (language_name, language_mark) VALUES('Frisian', 'fy');
INSERT INTO languages (language_name, language_mark) VALUES('Irish', 'ga');
INSERT INTO languages (language_name, language_mark) VALUES('Scots/Gaelic', 'gd');
INSERT INTO languages (language_name, language_mark) VALUES('Galician', 'gl');
INSERT INTO languages (language_name, language_mark) VALUES('Guarani', 'gn');
INSERT INTO languages (language_name, language_mark) VALUES('Gujarati', 'gu');
INSERT INTO languages (language_name, language_mark) VALUES('Hausa', 'ha');
INSERT INTO languages (language_name, language_mark) VALUES('Hindi', 'hi');
INSERT INTO languages (language_name, language_mark) VALUES('Croatian', 'hr');
INSERT INTO languages (language_name, language_mark) VALUES('Hungarian', 'hu');
INSERT INTO languages (language_name, language_mark) VALUES('Armenian', 'hy');
INSERT INTO languages (language_name, language_mark) VALUES('Interlingua', 'ia');
INSERT INTO languages (language_name, language_mark) VALUES('Interlingue', 'ie');
INSERT INTO languages (language_name, language_mark) VALUES('Inupiak', 'ik');
INSERT INTO languages (language_name, language_mark) VALUES('Indonesian', 'in');
INSERT INTO languages (language_name, language_mark) VALUES('Icelandic', 'is');
INSERT INTO languages (language_name, language_mark) VALUES('Italian', 'it');
INSERT INTO languages (language_name, language_mark) VALUES('Hebrew', 'iw');
INSERT INTO languages (language_name, language_mark) VALUES('Japanese', 'ja');
INSERT INTO languages (language_name, language_mark) VALUES('Yiddish', 'ji');
INSERT INTO languages (language_name, language_mark) VALUES('Javanese', 'jw');
INSERT INTO languages (language_name, language_mark) VALUES('Georgian', 'ka');
INSERT INTO languages (language_name, language_mark) VALUES('Kazakh', 'kk');
INSERT INTO languages (language_name, language_mark) VALUES('Greenlandic', 'kl');
INSERT INTO languages (language_name, language_mark) VALUES('Cambodian', 'km');
INSERT INTO languages (language_name, language_mark) VALUES('Kannada', 'kn');
INSERT INTO languages (language_name, language_mark) VALUES('Korean', 'ko');
INSERT INTO languages (language_name, language_mark) VALUES('Kashmiri', 'ks');
INSERT INTO languages (language_name, language_mark) VALUES('Kurdish', 'ku');
INSERT INTO languages (language_name, language_mark) VALUES('Kirghiz', 'ky');
INSERT INTO languages (language_name, language_mark) VALUES('Latin', 'la');
INSERT INTO languages (language_name, language_mark) VALUES('Lingala', 'ln');
INSERT INTO languages (language_name, language_mark) VALUES('Laothian', 'lo');
INSERT INTO languages (language_name, language_mark) VALUES('Lithuanian', 'lt');
INSERT INTO languages (language_name, language_mark) VALUES('Latvian/Lettish', 'lv');
INSERT INTO languages (language_name, language_mark) VALUES('Malagasy', 'mg');
INSERT INTO languages (language_name, language_mark) VALUES('Maori', 'mi');
INSERT INTO languages (language_name, language_mark) VALUES('Macedonian', 'mk');
INSERT INTO languages (language_name, language_mark) VALUES('Malayalam', 'ml');
INSERT INTO languages (language_name, language_mark) VALUES('Mongolian', 'mn');
INSERT INTO languages (language_name, language_mark) VALUES('Moldavian', 'mo');
INSERT INTO languages (language_name, language_mark) VALUES('Marathi', 'mr');
INSERT INTO languages (language_name, language_mark) VALUES('Malay', 'ms');
INSERT INTO languages (language_name, language_mark) VALUES('Maltese', 'mt');
INSERT INTO languages (language_name, language_mark) VALUES('Burmese', 'my');
INSERT INTO languages (language_name, language_mark) VALUES('Nauru', 'na');
INSERT INTO languages (language_name, language_mark) VALUES('Nepali', 'ne');
INSERT INTO languages (language_name, language_mark) VALUES('Dutch', 'nl');
INSERT INTO languages (language_name, language_mark) VALUES('Norwegian', 'no');
INSERT INTO languages (language_name, language_mark) VALUES('Occitan', 'oc');
INSERT INTO languages (language_name, language_mark) VALUES('(Afan)/Oromoor/Oriya', 'om');
INSERT INTO languages (language_name, language_mark) VALUES('Punjabi', 'pa');
INSERT INTO languages (language_name, language_mark) VALUES('Polish', 'pl');
INSERT INTO languages (language_name, language_mark) VALUES('Pashto/Pushto', 'ps');
INSERT INTO languages (language_name, language_mark) VALUES('Portuguese', 'pt');
INSERT INTO languages (language_name, language_mark) VALUES('Quechua', 'qu');
INSERT INTO languages (language_name, language_mark) VALUES('Rhaeto-Romance', 'rm');
INSERT INTO languages (language_name, language_mark) VALUES('Kirundi', 'rn');
INSERT INTO languages (language_name, language_mark) VALUES('Romanian', 'ro');
INSERT INTO languages (language_name, language_mark) VALUES('Russian', 'ru');
INSERT INTO languages (language_name, language_mark) VALUES('Kinyarwanda', 'rw');
INSERT INTO languages (language_name, language_mark) VALUES('Sanskrit', 'sa');
INSERT INTO languages (language_name, language_mark) VALUES('Sindhi', 'sd');
INSERT INTO languages (language_name, language_mark) VALUES('Sangro', 'sg');
INSERT INTO languages (language_name, language_mark) VALUES('Serbo-Croatian', 'sh');
INSERT INTO languages (language_name, language_mark) VALUES('Singhalese', 'si');
INSERT INTO languages (language_name, language_mark) VALUES('Slovak', 'sk');
INSERT INTO languages (language_name, language_mark) VALUES('Slovenian', 'sl');
INSERT INTO languages (language_name, language_mark) VALUES('Samoan', 'sm');
INSERT INTO languages (language_name, language_mark) VALUES('Shona', 'sn');
INSERT INTO languages (language_name, language_mark) VALUES('Somali', 'so');
INSERT INTO languages (language_name, language_mark) VALUES('Albanian', 'sq');
INSERT INTO languages (language_name, language_mark) VALUES('Serbian', 'sr');
INSERT INTO languages (language_name, language_mark) VALUES('Siswati', 'ss');
INSERT INTO languages (language_name, language_mark) VALUES('Sesotho', 'st');
INSERT INTO languages (language_name, language_mark) VALUES('Sundanese', 'su');
INSERT INTO languages (language_name, language_mark) VALUES('Swedish', 'sv');
INSERT INTO languages (language_name, language_mark) VALUES('Swahili', 'sw');
INSERT INTO languages (language_name, language_mark) VALUES('Tamil', 'ta');
INSERT INTO languages (language_name, language_mark) VALUES('Telugu', 'te');
INSERT INTO languages (language_name, language_mark) VALUES('Tajik', 'tg');
INSERT INTO languages (language_name, language_mark) VALUES('Thai', 'th');
INSERT INTO languages (language_name, language_mark) VALUES('Tigrinya', 'ti');
INSERT INTO languages (language_name, language_mark) VALUES('Turkmen', 'tk');
INSERT INTO languages (language_name, language_mark) VALUES('Tagalog', 'tl');
INSERT INTO languages (language_name, language_mark) VALUES('Setswana', 'tn');
INSERT INTO languages (language_name, language_mark) VALUES('Tonga', 'to');
INSERT INTO languages (language_name, language_mark) VALUES('Turkish', 'tr');
INSERT INTO languages (language_name, language_mark) VALUES('Tsonga', 'ts');
INSERT INTO languages (language_name, language_mark) VALUES('Tatar', 'tt');
INSERT INTO languages (language_name, language_mark) VALUES('Twi', 'tw');
INSERT INTO languages (language_name, language_mark) VALUES('Ukrainian', 'uk');
INSERT INTO languages (language_name, language_mark) VALUES('Urdu', 'ur');
INSERT INTO languages (language_name, language_mark) VALUES('Uzbek', 'uz');
INSERT INTO languages (language_name, language_mark) VALUES('Vietnamese', 'vi');
INSERT INTO languages (language_name, language_mark) VALUES('Volapuk', 'vo');
INSERT INTO languages (language_name, language_mark) VALUES('Wolof', 'wo');
INSERT INTO languages (language_name, language_mark) VALUES('Xhosa', 'xh');
INSERT INTO languages (language_name, language_mark) VALUES('Yoruba', 'yo');
INSERT INTO languages (language_name, language_mark) VALUES('Chinese', 'zh');
INSERT INTO languages (language_name, language_mark) VALUES('Zulu', 'zu');


-- Insert currency records
INSERT INTO currency (country, currency, code, symbol) VALUES ('Albania', 'Leke', 'ALL', 'Lek');
INSERT INTO currency (country, currency, code, symbol) VALUES ('America', 'Dollars', 'USD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Afghanistan', 'Afghanis', 'AFN', '؋');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Argentina', 'Pesos', 'ARS', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Aruba', 'Guilders', 'AWG', 'ƒ');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Australia', 'Dollars', 'AUD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Azerbaijan', 'New Manats', 'AZN', 'ман');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Bahamas', 'Dollars', 'BSD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Barbados', 'Dollars', 'BBD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Belarus', 'Rubles', 'BYR', 'p.');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Belgium', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Beliz', 'Dollars', 'BZD', 'BZ$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Bermuda', 'Dollars', 'BMD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Bolivia', 'Bolivianos', 'BOB', '$b');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Bosnia and Herzegovina', 'Convertible Marka', 'BAM', 'KM');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Botswana', 'Pula', 'BWP', 'P');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Bulgaria', 'Leva', 'BGN', 'лв');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Brazil', 'Reais', 'BRL', 'R$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Britain (United Kingdom)', 'Pounds', 'GBP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Brunei Darussalam', 'Dollars', 'BND', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Cambodia', 'Riels', 'KHR', '៛');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Canada', 'Dollars', 'CAD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Cayman Islands', 'Dollars', 'KYD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Chile', 'Pesos', 'CLP', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('China', 'Yuan Renminbi', 'CNY', '¥');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Colombia', 'Pesos', 'COP', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Costa Rica', 'Colón', 'CRC', '₡');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Croatia', 'Kuna', 'HRK', 'kn');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Cuba', 'Pesos', 'CUP', '₱');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Cyprus', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Czech Republic', 'Koruny', 'CZK', 'Kč');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Denmark', 'Kroner', 'DKK', 'kr');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Dominican Republic', 'Pesos', 'DOP ', 'RD$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('East Caribbean', 'Dollars', 'XCD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Egypt', 'Pounds', 'EGP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('El Salvador', 'Colones', 'SVC', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('England (United Kingdom)', 'Pounds', 'GBP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Euro', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Falkland Islands', 'Pounds', 'FKP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Fiji', 'Dollars', 'FJD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('France', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Ghana', 'Cedis', 'GHC', '¢');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Gibraltar', 'Pounds', 'GIP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Greece', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Guatemala', 'Quetzales', 'GTQ', 'Q');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Guernsey', 'Pounds', 'GGP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Guyana', 'Dollars', 'GYD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Holland (Netherlands)', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Honduras', 'Lempiras', 'HNL', 'L');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Hong Kong', 'Dollars', 'HKD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Hungary', 'Forint', 'HUF', 'Ft');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Iceland', 'Kronur', 'ISK', 'kr');
INSERT INTO currency (country, currency, code, symbol) VALUES ('India', 'Rupees', 'INR', 'Rp');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Indonesia', 'Rupiahs', 'IDR', 'Rp');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Iran', 'Rials', 'IRR', '﷼');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Ireland', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Isle of Man', 'Pounds', 'IMP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Israel', 'New Shekels', 'ILS', '₪');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Italy', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Jamaica', 'Dollars', 'JMD', 'J$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Japan', 'Yen', 'JPY', '¥');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Jersey', 'Pounds', 'JEP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Kazakhstan', 'Tenge', 'KZT', 'лв');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Korea (North)', 'Won', 'KPW', '₩');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Korea (South)', 'Won', 'KRW', '₩');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Kyrgyzstan', 'Soms', 'KGS', 'лв');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Laos', 'Kips', 'LAK', '₭');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Latvia', 'Lati', 'LVL', 'Ls');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Lebanon', 'Pounds', 'LBP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Liberia', 'Dollars', 'LRD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Liechtenstein', 'Switzerland Francs', 'CHF', 'CHF');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Lithuania', 'Litai', 'LTL', 'Lt');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Luxembourg', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Macedonia', 'Denars', 'MKD', 'ден');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Malaysia', 'Ringgits', 'MYR', 'RM');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Malta', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Mauritius', 'Rupees', 'MUR', '₨');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Mexico', 'Pesos', 'MXN', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Mongolia', 'Tugriks', 'MNT', '₮');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Mozambique', 'Meticais', 'MZN', 'MT');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Namibia', 'Dollars', 'NAD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Nepal', 'Rupees', 'NPR', '₨');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Netherlands Antilles', 'Guilders', 'ANG', 'ƒ');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Netherlands', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('New Zealand', 'Dollars', 'NZD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Nicaragua', 'Cordobas', 'NIO', 'C$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Nigeria', 'Nairas', 'NGN', '₦');
INSERT INTO currency (country, currency, code, symbol) VALUES ('North Korea', 'Won', 'KPW', '₩');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Norway', 'Krone', 'NOK', 'kr');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Oman', 'Rials', 'OMR', '﷼');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Pakistan', 'Rupees', 'PKR', '₨');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Panama', 'Balboa', 'PAB', 'B/.');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Paraguay', 'Guarani', 'PYG', 'Gs');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Peru', 'Nuevos Soles', 'PEN', 'S/.');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Philippines', 'Pesos', 'PHP', 'Php');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Poland', 'Zlotych', 'PLN', 'zł');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Qatar', 'Rials', 'QAR', '﷼');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Romania', 'New Lei', 'RON', 'lei');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Russia', 'Rubles', 'RUB', 'руб');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Saint Helena', 'Pounds', 'SHP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Saudi Arabia', 'Riyals', 'SAR', '﷼');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Serbia', 'Dinars', 'RSD', 'Дин.');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Seychelles', 'Rupees', 'SCR', '₨');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Singapore', 'Dollars', 'SGD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Slovenia', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Solomon Islands', 'Dollars', 'SBD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Somalia', 'Shillings', 'SOS', 'S');
INSERT INTO currency (country, currency, code, symbol) VALUES ('South Africa', 'Rand', 'ZAR', 'R');
INSERT INTO currency (country, currency, code, symbol) VALUES ('South Korea', 'Won', 'KRW', '₩');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Spain', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Sri Lanka', 'Rupees', 'LKR', '₨');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Sweden', 'Kronor', 'SEK', 'kr');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Switzerland', 'Francs', 'CHF', 'CHF');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Suriname', 'Dollars', 'SRD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Syria', 'Pounds', 'SYP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Taiwan', 'New Dollars', 'TWD', 'NT$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Thailand', 'Baht', 'THB', '฿');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Trinidad and Tobago', 'Dollars', 'TTD', 'TT$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Turkey', 'Lira', 'TRY', 'TL');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Turkey', 'Liras', 'TRL', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Tuvalu', 'Dollars', 'TVD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Ukraine', 'Hryvnia', 'UAH', '₴');
INSERT INTO currency (country, currency, code, symbol) VALUES ('United Kingdom', 'Pounds', 'GBP', '£');
INSERT INTO currency (country, currency, code, symbol) VALUES ('United States of America', 'Dollars', 'USD', '$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Uruguay', 'Pesos', 'UYU', '$U');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Uzbekistan', 'Sums', 'UZS', 'лв');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Vatican City', 'Euro', 'EUR', '€');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Venezuela', 'Bolivares Fuertes', 'VEF', 'Bs');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Vietnam', 'Dong', 'VND', '₫');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Yemen', 'Rials', 'YER', '﷼');
INSERT INTO currency (country, currency, code, symbol) VALUES ('Zimbabwe', 'Zimbabwe Dollars', 'ZWD', 'Z$');
INSERT INTO currency (country, currency, code, symbol) VALUES ('India', 'Rupees', 'INR', '₹');

--Products
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('21.02.2020', 2, 'Product desc', 2, 20.20, 'name1', '20.02.2022');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('22.02.2020', 2, 'Product desc', 2, 20.20, 'name2', '20.02.2022');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('23.02.2020', 2, 'Product desc', 2, 20.20, 'name3', '20.02.2022');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('24.02.2020', 2, 'Product desc', 2, 20.20, 'name4', '20.02.2102');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('25.02.2020', 2, 'Product desc', 2, 20.20, 'name5', '20.02.2202');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('26.02.2020', 1, 'Product desc', 2, 20.20, 'name6', '20.02.2102');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('27.02.2020', 1, 'Product desc', 2, 20.20, 'name7', '20.02.2102');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('28.02.2020', 27, 'Product desc', 5, 20.20, 'name8', '20.02.2102');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('28.02.2020', 24, 'Product desc', 7, 20.20, 'name9', '20.02.2012');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('01.03.2020', 12, 'Product desc', 8, 20.20, 'name10', '20.02.2102');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('02.03.2020', 3, 'Product desc', 7, 20.20, 'name11', '20.02.2012');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('03.03.2020', 3, 'Product desc', 7, 20.20, 'name12', '20.02.2102');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('04.03.2020', 3, 'Product desc', 4, 20.20, 'name13', '20.02.2012');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('05.03.2020', 6, 'Product desc', 2, 20.20, 'name14', '20.02.2012');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('06.03.2020', 8, 'Product desc', 2, 20.20, 'name15', '20.02.2012');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('07.03.2020', 8, 'Product desc', 7, 20.20, 'name16', '20.02.2202');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('08.03.2020', 9, 'Product desc', 5, 20.20, 'name17', '20.02.2001');
insert into products (create_date, currency_id, description, lang_id, price, product_name, update_date)
values ('09.03.2020', 10, 'Product desc', 2, 20.20, 'name18', '20.02.2002');